// Generated by jextract

package io.github.thecodecrafters.craftingcode.lua.foreign;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$27 {

    static final FunctionDescriptor eris_unpersist$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle eris_unpersist$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "eris_unpersist",
        "(Ljdk/incubator/foreign/MemoryAddress;II)V",
        constants$27.eris_unpersist$FUNC, false
    );
    static final FunctionDescriptor eris_get_setting$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle eris_get_setting$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "eris_get_setting",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$27.eris_get_setting$FUNC, false
    );
    static final FunctionDescriptor eris_set_setting$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle eris_set_setting$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "eris_set_setting",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)V",
        constants$27.eris_set_setting$FUNC, false
    );
    static final MemorySegment LUA_PATH_SEP$SEGMENT = CLinker.toCString(";", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_PATH_MARK$SEGMENT = CLinker.toCString("?", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_VDIR$SEGMENT = CLinker.toCString("5.3", ResourceScope.newImplicitScope());
}


