// Generated by jextract

package io.github.thecodecrafters.craftingcode.lua.foreign;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$30 {

    static final MemorySegment LUA_SIGNATURE$SEGMENT = CLinker.toCString("\u001bLua", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_VERSUFFIX$SEGMENT = CLinker.toCString("_5_3", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_COLIBNAME$SEGMENT = CLinker.toCString("coroutine", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_TABLIBNAME$SEGMENT = CLinker.toCString("table", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_IOLIBNAME$SEGMENT = CLinker.toCString("io", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_OSLIBNAME$SEGMENT = CLinker.toCString("os", ResourceScope.newImplicitScope());
}


