// Generated by jextract

package io.github.thecodecrafters.craftingcode.lua.foreign;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;

import static io.github.thecodecrafters.craftingcode.lua.foreign.Lua.*;
import static jdk.incubator.foreign.CLinker.*;
import static jdk.incubator.foreign.MemoryLayouts.ADDRESS;

class constants$7 {

    static final FunctionDescriptor lua_pushnil$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle lua_pushnil$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "lua_pushnil",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$7.lua_pushnil$FUNC, false
    );
    static final FunctionDescriptor lua_pushnumber$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        lua_Number
    );
    static final MethodHandle lua_pushnumber$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "lua_pushnumber",
        "(Ljdk/incubator/foreign/MemoryAddress;D)V",
        constants$7.lua_pushnumber$FUNC, false
    );
    static final FunctionDescriptor lua_pushinteger$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        lua_Integer
    );
    static final MethodHandle lua_pushinteger$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "lua_pushinteger",
        "(Ljdk/incubator/foreign/MemoryAddress;J)V",
        constants$7.lua_pushinteger$FUNC, false
    );
    static final FunctionDescriptor lua_pushlstring$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        size_t
    );
    static final MethodHandle lua_pushlstring$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "lua_pushlstring",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)Ljdk/incubator/foreign/MemoryAddress;",
        constants$7.lua_pushlstring$FUNC, false
    );
    static final FunctionDescriptor lua_pushstring$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle lua_pushstring$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "lua_pushstring",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$7.lua_pushstring$FUNC, false
    );
    static final FunctionDescriptor lua_pushvfstring$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle lua_pushvfstring$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "lua_pushvfstring",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$7.lua_pushvfstring$FUNC, false
    );
}


