// Generated by jextract

package io.github.thecodecrafters.craftingcode.lua.foreign;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$31 {

    static final MemorySegment LUA_STRLIBNAME$SEGMENT = CLinker.toCString("string", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_UTF8LIBNAME$SEGMENT = CLinker.toCString("utf8", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_BITLIBNAME$SEGMENT = CLinker.toCString("bit32", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_MATHLIBNAME$SEGMENT = CLinker.toCString("math", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_DBLIBNAME$SEGMENT = CLinker.toCString("debug", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_LOADLIBNAME$SEGMENT = CLinker.toCString("package", ResourceScope.newImplicitScope());
}


