// Generated by jextract

package io.github.thecodecrafters.craftingcode.lua.foreign;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$32 {

    static final MemorySegment LUA_ERISLIBNAME$SEGMENT = CLinker.toCString("eris", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_LOADED_TABLE$SEGMENT = CLinker.toCString("_LOADED", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_PRELOAD_TABLE$SEGMENT = CLinker.toCString("_PRELOAD", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_FILEHANDLE$SEGMENT = CLinker.toCString("FILE*", ResourceScope.newImplicitScope());
    static final MemorySegment ERIS_VERSION_MAJOR$SEGMENT = CLinker.toCString("1", ResourceScope.newImplicitScope());
    static final MemorySegment ERIS_VERSION_MINOR$SEGMENT = CLinker.toCString("1", ResourceScope.newImplicitScope());
}


