// Generated by jextract

package io.github.thecodecrafters.craftingcode.lua.foreign;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
import static jdk.incubator.foreign.MemoryLayouts.ADDRESS;

class constants$26 {

    static final FunctionDescriptor luaL_pushresult$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle luaL_pushresult$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "luaL_pushresult",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$26.luaL_pushresult$FUNC, false
    );
    static final FunctionDescriptor luaL_pushresultsize$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        ADDRESS
    );
    static final MethodHandle luaL_pushresultsize$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "luaL_pushresultsize",
        "(Ljdk/incubator/foreign/MemoryAddress;J)V",
        constants$26.luaL_pushresultsize$FUNC, false
    );
    static final FunctionDescriptor luaL_buffinitsize$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        ADDRESS
    );
    static final MethodHandle luaL_buffinitsize$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "luaL_buffinitsize",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)Ljdk/incubator/foreign/MemoryAddress;",
        constants$26.luaL_buffinitsize$FUNC, false
    );
    static final FunctionDescriptor eris_dump$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle eris_dump$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "eris_dump",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$26.eris_dump$FUNC, false
    );
    static final FunctionDescriptor eris_undump$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle eris_undump$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "eris_undump",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$26.eris_undump$FUNC, false
    );
    static final FunctionDescriptor eris_persist$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle eris_persist$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "eris_persist",
        "(Ljdk/incubator/foreign/MemoryAddress;II)V",
        constants$26.eris_persist$FUNC, false
    );
}


