// Generated by jextract

package io.github.thecodecrafters.craftingcode.lua.foreign;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$33 {

    static final MemorySegment ERIS_VERSION_RELEASE$SEGMENT = CLinker.toCString("3", ResourceScope.newImplicitScope());
}


