// Generated by jextract

package io.github.thecodecrafters.craftingcode.lua.foreign;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$9 {

    static final FunctionDescriptor lua_gettable$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle lua_gettable$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "lua_gettable",
        "(Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$9.lua_gettable$FUNC, false
    );
    static final FunctionDescriptor lua_getfield$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle lua_getfield$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "lua_getfield",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$9.lua_getfield$FUNC, false
    );
    static final FunctionDescriptor lua_geti$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_LONG_LONG
    );
    static final MethodHandle lua_geti$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "lua_geti",
        "(Ljdk/incubator/foreign/MemoryAddress;IJ)I",
        constants$9.lua_geti$FUNC, false
    );
    static final FunctionDescriptor lua_rawget$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle lua_rawget$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "lua_rawget",
        "(Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$9.lua_rawget$FUNC, false
    );
    static final FunctionDescriptor lua_rawgeti$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_LONG_LONG
    );
    static final MethodHandle lua_rawgeti$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "lua_rawgeti",
        "(Ljdk/incubator/foreign/MemoryAddress;IJ)I",
        constants$9.lua_rawgeti$FUNC, false
    );
    static final FunctionDescriptor lua_rawgetp$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle lua_rawgetp$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "lua_rawgetp",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$9.lua_rawgetp$FUNC, false
    );
}


