// Generated by jextract

package io.github.thecodecrafters.craftingcode.lua.foreign;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$29 {

    static final MemorySegment LUA_VERSION_MINOR$SEGMENT = CLinker.toCString("3", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_VERSION_RELEASE$SEGMENT = CLinker.toCString("5", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_VERSION$SEGMENT = CLinker.toCString("Lua+Eris 5.3", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_RELEASE$SEGMENT = CLinker.toCString("Lua+Eris 5.3.5", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_COPYRIGHT$SEGMENT = CLinker.toCString("Lua+Eris 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_AUTHORS$SEGMENT = CLinker.toCString("R. Ierusalimschy, L. H. de Figueiredo, W. Celes", ResourceScope.newImplicitScope());
}


