// Generated by jextract

package io.github.thecodecrafters.craftingcode.lua.foreign;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$28 {

    static final MemorySegment LUA_NUMBER_FRMLEN$SEGMENT = CLinker.toCString("", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_NUMBER_FMT$SEGMENT = CLinker.toCString("%.14g", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_INTEGER_FMT$SEGMENT = CLinker.toCString("%lld", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_INTEGER_FRMLEN$SEGMENT = CLinker.toCString("ll", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_QS$SEGMENT = CLinker.toCString("\'%s\'", ResourceScope.newImplicitScope());
    static final MemorySegment LUA_VERSION_MAJOR$SEGMENT = CLinker.toCString("5", ResourceScope.newImplicitScope());
}


