// Generated by jextract

package io.github.thecodecrafters.craftingcode.lua.foreign;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$8 {

    static final FunctionDescriptor lua_pushfstring$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle lua_pushfstring$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "lua_pushfstring",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$8.lua_pushfstring$FUNC, true
    );
    static final FunctionDescriptor lua_pushcclosure$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle lua_pushcclosure$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "lua_pushcclosure",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)V",
        constants$8.lua_pushcclosure$FUNC, false
    );
    static final FunctionDescriptor lua_pushboolean$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT
    );
    static final MethodHandle lua_pushboolean$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "lua_pushboolean",
        "(Ljdk/incubator/foreign/MemoryAddress;I)V",
        constants$8.lua_pushboolean$FUNC, false
    );
    static final FunctionDescriptor lua_pushlightuserdata$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle lua_pushlightuserdata$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "lua_pushlightuserdata",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$8.lua_pushlightuserdata$FUNC, false
    );
    static final FunctionDescriptor lua_pushthread$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle lua_pushthread$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "lua_pushthread",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$8.lua_pushthread$FUNC, false
    );
    static final FunctionDescriptor lua_getglobal$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle lua_getglobal$MH = RuntimeHelper.downcallHandle(
        Lua.LIBRARIES, "lua_getglobal",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$8.lua_getglobal$FUNC, false
    );
}


