// Generated by jextract

package io.github.thecodecrafters.craftingcode.lua.foreign;

import java.lang.invoke.MethodHandle;

import jdk.incubator.foreign.*;

import org.jetbrains.annotations.NotNull;

import static jdk.incubator.foreign.CLinker.*;
import static jdk.incubator.foreign.MemoryAddress.NULL;

public class Lua  {

    static {
        System.loadLibrary("lua");
    }

    static final SymbolLookup LIBRARIES = RuntimeHelper.lookup();    /* package-private */ Lua() {}
    public static int LUAI_BITSINT() {
        return (int)32L;
    }
    public static int LUA_INT_INT() {
        return (int)1L;
    }
    public static int LUA_INT_LONG() {
        return (int)2L;
    }
    public static int LUA_INT_LONGLONG() {
        return (int)3L;
    }
    public static int LUA_FLOAT_FLOAT() {
        return (int)1L;
    }
    public static int LUA_FLOAT_DOUBLE() {
        return (int)2L;
    }
    public static int LUA_FLOAT_LONGDOUBLE() {
        return (int)3L;
    }
    public static int LUAI_MAXSTACK() {
        return (int)1000000L;
    }
    public static int LUA_IDSIZE() {
        return (int)60L;
    }
    public static int LUA_VERSION_NUM() {
        return (int)503L;
    }
    public static int LUA_OK() {
        return (int)0L;
    }
    public static int LUA_YIELD() {
        return (int)1L;
    }
    public static int LUA_ERRRUN() {
        return (int)2L;
    }
    public static int LUA_ERRSYNTAX() {
        return (int)3L;
    }
    public static int LUA_ERRMEM() {
        return (int)4L;
    }
    public static int LUA_ERRGCMM() {
        return (int)5L;
    }
    public static int LUA_ERRERR() {
        return (int)6L;
    }
    public static int LUA_TNIL() {
        return (int)0L;
    }
    public static int LUA_TBOOLEAN() {
        return (int)1L;
    }
    public static int LUA_TLIGHTUSERDATA() {
        return (int)2L;
    }
    public static int LUA_TNUMBER() {
        return (int)3L;
    }
    public static int LUA_TSTRING() {
        return (int)4L;
    }
    public static int LUA_TTABLE() {
        return (int)5L;
    }
    public static int LUA_TFUNCTION() {
        return (int)6L;
    }
    public static int LUA_TUSERDATA() {
        return (int)7L;
    }
    public static int LUA_TTHREAD() {
        return (int)8L;
    }
    public static int LUA_NUMTAGS() {
        return (int)9L;
    }
    public static int LUA_MINSTACK() {
        return (int)20L;
    }
    public static int LUA_RIDX_MAINTHREAD() {
        return (int)1L;
    }
    public static int LUA_RIDX_GLOBALS() {
        return (int)2L;
    }
    public static int LUA_OPADD() {
        return (int)0L;
    }
    public static int LUA_OPSUB() {
        return (int)1L;
    }
    public static int LUA_OPMUL() {
        return (int)2L;
    }
    public static int LUA_OPMOD() {
        return (int)3L;
    }
    public static int LUA_OPPOW() {
        return (int)4L;
    }
    public static int LUA_OPDIV() {
        return (int)5L;
    }
    public static int LUA_OPIDIV() {
        return (int)6L;
    }
    public static int LUA_OPBAND() {
        return (int)7L;
    }
    public static int LUA_OPBOR() {
        return (int)8L;
    }
    public static int LUA_OPBXOR() {
        return (int)9L;
    }
    public static int LUA_OPSHL() {
        return (int)10L;
    }
    public static int LUA_OPSHR() {
        return (int)11L;
    }
    public static int LUA_OPUNM() {
        return (int)12L;
    }
    public static int LUA_OPBNOT() {
        return (int)13L;
    }
    public static int LUA_OPEQ() {
        return (int)0L;
    }
    public static int LUA_OPLT() {
        return (int)1L;
    }
    public static int LUA_OPLE() {
        return (int)2L;
    }
    public static int LUA_GCSTOP() {
        return (int)0L;
    }
    public static int LUA_GCRESTART() {
        return (int)1L;
    }
    public static int LUA_GCCOLLECT() {
        return (int)2L;
    }
    public static int LUA_GCCOUNT() {
        return (int)3L;
    }
    public static int LUA_GCCOUNTB() {
        return (int)4L;
    }
    public static int LUA_GCSTEP() {
        return (int)5L;
    }
    public static int LUA_GCSETPAUSE() {
        return (int)6L;
    }
    public static int LUA_GCSETSTEPMUL() {
        return (int)7L;
    }
    public static int LUA_GCISRUNNING() {
        return (int)9L;
    }
    public static int LUA_HOOKCALL() {
        return (int)0L;
    }
    public static int LUA_HOOKRET() {
        return (int)1L;
    }
    public static int LUA_HOOKLINE() {
        return (int)2L;
    }
    public static int LUA_HOOKCOUNT() {
        return (int)3L;
    }
    public static int LUA_HOOKTAILCALL() {
        return (int)4L;
    }
    public static int ERIS_VERSION_NUM() {
        return (int)101L;
    }
    public static final ValueLayout lua_Number = C_DOUBLE;
    public static final ValueLayout lua_Integer = C_LONG_LONG;
    public static final ValueLayout size_t = C_LONG_LONG;
    public static final ValueLayout lua_KContext = size_t;
    public static final FunctionDescriptor lua_CFunction = constants$0.lua_CFunction$FUNC;
    static {
        if (C_LONG_LONG.byteSize() != C_POINTER.byteSize() || C_LONG_LONG.bitSize() != C_POINTER.bitSize()
                || C_LONG_LONG.bitAlignment() != C_POINTER.bitAlignment() || C_LONG_LONG.byteAlignment() != C_POINTER.byteAlignment())
            throw new AssertionError("C_POINTER should match C_LONG_LONG"); // because otherwise size_t is incorrect
    }
    public static MethodHandle lua_newstate$MH() {
        return RuntimeHelper.requireNonNull(constants$1.lua_newstate$MH,"lua_newstate");
    }
    public static MemoryAddress lua_newstate ( Addressable f,  Addressable ud) {
        var mh$ = RuntimeHelper.requireNonNull(constants$1.lua_newstate$MH, "lua_newstate");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(f.address(), ud.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_close$MH() {
        return RuntimeHelper.requireNonNull(constants$1.lua_close$MH,"lua_close");
    }
    public static void lua_close ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$1.lua_close$MH, "lua_close");
        try {
            mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_newthread$MH() {
        return RuntimeHelper.requireNonNull(constants$2.lua_newthread$MH,"lua_newthread");
    }
    public static MemoryAddress lua_newthread ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$2.lua_newthread$MH, "lua_newthread");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_atpanic$MH() {
        return RuntimeHelper.requireNonNull(constants$2.lua_atpanic$MH,"lua_atpanic");
    }
    public static MemoryAddress lua_atpanic ( @NotNull Addressable L,  Addressable panicf) {
        var mh$ = RuntimeHelper.requireNonNull(constants$2.lua_atpanic$MH, "lua_atpanic");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), panicf.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_version$MH() {
        return RuntimeHelper.requireNonNull(constants$2.lua_version$MH,"lua_version");
    }
    public static MemoryAddress lua_version ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$2.lua_version$MH, "lua_version");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_absindex$MH() {
        return RuntimeHelper.requireNonNull(constants$2.lua_absindex$MH,"lua_absindex");
    }
    public static int lua_absindex ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$2.lua_absindex$MH, "lua_absindex");
        try {
            return (int)mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_gettop$MH() {
        return RuntimeHelper.requireNonNull(constants$2.lua_gettop$MH,"lua_gettop");
    }
    public static int lua_gettop ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$2.lua_gettop$MH, "lua_gettop");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_settop$MH() {
        return RuntimeHelper.requireNonNull(constants$2.lua_settop$MH,"lua_settop");
    }
    public static void lua_settop ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$2.lua_settop$MH, "lua_settop");
        try {
            mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_pushvalue$MH() {
        return RuntimeHelper.requireNonNull(constants$3.lua_pushvalue$MH,"lua_pushvalue");
    }
    public static void lua_pushvalue ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$3.lua_pushvalue$MH, "lua_pushvalue");
        try {
            mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_rotate$MH() {
        return RuntimeHelper.requireNonNull(constants$3.lua_rotate$MH,"lua_rotate");
    }
    public static void lua_rotate ( @NotNull Addressable L,  int idx,  int n) {
        var mh$ = RuntimeHelper.requireNonNull(constants$3.lua_rotate$MH, "lua_rotate");
        try {
            mh$.invokeExact(L.address(), idx, n);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_copy$MH() {
        return RuntimeHelper.requireNonNull(constants$3.lua_copy$MH,"lua_copy");
    }
    public static void lua_copy ( @NotNull Addressable L,  int fromidx,  int toidx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$3.lua_copy$MH, "lua_copy");
        try {
            mh$.invokeExact(L.address(), fromidx, toidx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_checkstack$MH() {
        return RuntimeHelper.requireNonNull(constants$3.lua_checkstack$MH,"lua_checkstack");
    }
    public static int lua_checkstack ( @NotNull Addressable L,  int n) {
        var mh$ = RuntimeHelper.requireNonNull(constants$3.lua_checkstack$MH, "lua_checkstack");
        try {
            return (int)mh$.invokeExact(L.address(), n);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_xmove$MH() {
        return RuntimeHelper.requireNonNull(constants$3.lua_xmove$MH,"lua_xmove");
    }
    public static void lua_xmove ( Addressable from,  Addressable to,  int n) {
        var mh$ = RuntimeHelper.requireNonNull(constants$3.lua_xmove$MH, "lua_xmove");
        try {
            mh$.invokeExact(from.address(), to.address(), n);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_isnumber$MH() {
        return RuntimeHelper.requireNonNull(constants$3.lua_isnumber$MH,"lua_isnumber");
    }
    public static int lua_isnumber ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$3.lua_isnumber$MH, "lua_isnumber");
        try {
            return (int)mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_isstring$MH() {
        return RuntimeHelper.requireNonNull(constants$4.lua_isstring$MH,"lua_isstring");
    }
    public static int lua_isstring ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$4.lua_isstring$MH, "lua_isstring");
        try {
            return (int)mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_iscfunction$MH() {
        return RuntimeHelper.requireNonNull(constants$4.lua_iscfunction$MH,"lua_iscfunction");
    }
    public static int lua_iscfunction ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$4.lua_iscfunction$MH, "lua_iscfunction");
        try {
            return (int)mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_isinteger$MH() {
        return RuntimeHelper.requireNonNull(constants$4.lua_isinteger$MH,"lua_isinteger");
    }
    public static int lua_isinteger ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$4.lua_isinteger$MH, "lua_isinteger");
        try {
            return (int)mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_isuserdata$MH() {
        return RuntimeHelper.requireNonNull(constants$4.lua_isuserdata$MH,"lua_isuserdata");
    }
    public static int lua_isuserdata ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$4.lua_isuserdata$MH, "lua_isuserdata");
        try {
            return (int)mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_type$MH() {
        return RuntimeHelper.requireNonNull(constants$4.lua_type$MH,"lua_type");
    }
    public static int lua_type ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$4.lua_type$MH, "lua_type");
        try {
            return (int)mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_typename$MH() {
        return RuntimeHelper.requireNonNull(constants$4.lua_typename$MH,"lua_typename");
    }
    public static MemoryAddress lua_typename ( @NotNull Addressable L,  int tp) {
        var mh$ = RuntimeHelper.requireNonNull(constants$4.lua_typename$MH, "lua_typename");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), tp);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_tonumberx$MH() {
        return RuntimeHelper.requireNonNull(constants$5.lua_tonumberx$MH,"lua_tonumberx");
    }
    public static double lua_tonumberx ( @NotNull Addressable L,  int idx,  Addressable isnum) {
        var mh$ = RuntimeHelper.requireNonNull(constants$5.lua_tonumberx$MH, "lua_tonumberx");
        try {
            return (double)mh$.invokeExact(L.address(), idx, isnum.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_tointegerx$MH() {
        return RuntimeHelper.requireNonNull(constants$5.lua_tointegerx$MH,"lua_tointegerx");
    }
    public static long lua_tointegerx ( @NotNull Addressable L,  int idx,  Addressable isnum) {
        var mh$ = RuntimeHelper.requireNonNull(constants$5.lua_tointegerx$MH, "lua_tointegerx");
        try {
            return (long)mh$.invokeExact(L.address(), idx, isnum.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_toboolean$MH() {
        return RuntimeHelper.requireNonNull(constants$5.lua_toboolean$MH,"lua_toboolean");
    }
    public static int lua_toboolean ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$5.lua_toboolean$MH, "lua_toboolean");
        try {
            return (int)mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_tolstring$MH() {
        return RuntimeHelper.requireNonNull(constants$5.lua_tolstring$MH,"lua_tolstring");
    }
    public static MemoryAddress lua_tolstring ( @NotNull Addressable L,  int idx,  Addressable len) {
        var mh$ = RuntimeHelper.requireNonNull(constants$5.lua_tolstring$MH, "lua_tolstring");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), idx, len.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_rawlen$MH() {
        return RuntimeHelper.requireNonNull(constants$5.lua_rawlen$MH,"lua_rawlen");
    }
    public static long lua_rawlen ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$5.lua_rawlen$MH, "lua_rawlen");
        try {
            return (long)mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_tocfunction$MH() {
        return RuntimeHelper.requireNonNull(constants$5.lua_tocfunction$MH,"lua_tocfunction");
    }
    public static MemoryAddress lua_tocfunction ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$5.lua_tocfunction$MH, "lua_tocfunction");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_touserdata$MH() {
        return RuntimeHelper.requireNonNull(constants$6.lua_touserdata$MH,"lua_touserdata");
    }
    public static MemoryAddress lua_touserdata ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$6.lua_touserdata$MH, "lua_touserdata");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_tothread$MH() {
        return RuntimeHelper.requireNonNull(constants$6.lua_tothread$MH,"lua_tothread");
    }
    public static MemoryAddress lua_tothread ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$6.lua_tothread$MH, "lua_tothread");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_topointer$MH() {
        return RuntimeHelper.requireNonNull(constants$6.lua_topointer$MH,"lua_topointer");
    }
    public static MemoryAddress lua_topointer ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$6.lua_topointer$MH, "lua_topointer");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_arith$MH() {
        return RuntimeHelper.requireNonNull(constants$6.lua_arith$MH,"lua_arith");
    }
    public static void lua_arith ( @NotNull Addressable L,  int op) {
        var mh$ = RuntimeHelper.requireNonNull(constants$6.lua_arith$MH, "lua_arith");
        try {
            mh$.invokeExact(L.address(), op);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_rawequal$MH() {
        return RuntimeHelper.requireNonNull(constants$6.lua_rawequal$MH,"lua_rawequal");
    }
    public static int lua_rawequal ( @NotNull Addressable L,  int idx1,  int idx2) {
        var mh$ = RuntimeHelper.requireNonNull(constants$6.lua_rawequal$MH, "lua_rawequal");
        try {
            return (int)mh$.invokeExact(L.address(), idx1, idx2);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_compare$MH() {
        return RuntimeHelper.requireNonNull(constants$6.lua_compare$MH,"lua_compare");
    }
    public static int lua_compare ( @NotNull Addressable L,  int idx1,  int idx2,  int op) {
        var mh$ = RuntimeHelper.requireNonNull(constants$6.lua_compare$MH, "lua_compare");
        try {
            return (int)mh$.invokeExact(L.address(), idx1, idx2, op);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_pushnil$MH() {
        return RuntimeHelper.requireNonNull(constants$7.lua_pushnil$MH,"lua_pushnil");
    }
    public static void lua_pushnil ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$7.lua_pushnil$MH, "lua_pushnil");
        try {
            mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_pushnumber$MH() {
        return RuntimeHelper.requireNonNull(constants$7.lua_pushnumber$MH,"lua_pushnumber");
    }
    public static void lua_pushnumber ( @NotNull Addressable L,  double n) {
        var mh$ = RuntimeHelper.requireNonNull(constants$7.lua_pushnumber$MH, "lua_pushnumber");
        try {
            mh$.invokeExact(L.address(), n);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_pushinteger$MH() {
        return RuntimeHelper.requireNonNull(constants$7.lua_pushinteger$MH,"lua_pushinteger");
    }
    public static void lua_pushinteger ( @NotNull Addressable L,  long n) {
        var mh$ = RuntimeHelper.requireNonNull(constants$7.lua_pushinteger$MH, "lua_pushinteger");
        try {
            mh$.invokeExact(L.address(), n);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_pushlstring$MH() {
        return RuntimeHelper.requireNonNull(constants$7.lua_pushlstring$MH,"lua_pushlstring");
    }
    public static MemoryAddress lua_pushlstring ( @NotNull Addressable L,  Addressable s,  long len) {
        var mh$ = RuntimeHelper.requireNonNull(constants$7.lua_pushlstring$MH, "lua_pushlstring");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), s.address(), len);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_pushstring$MH() {
        return RuntimeHelper.requireNonNull(constants$7.lua_pushstring$MH,"lua_pushstring");
    }
    public static MemoryAddress lua_pushstring ( @NotNull Addressable L,  Addressable s) {
        var mh$ = RuntimeHelper.requireNonNull(constants$7.lua_pushstring$MH, "lua_pushstring");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), s.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_pushvfstring$MH() {
        return RuntimeHelper.requireNonNull(constants$7.lua_pushvfstring$MH,"lua_pushvfstring");
    }
    public static MemoryAddress lua_pushvfstring ( @NotNull Addressable L,  Addressable fmt,  Addressable argp) {
        var mh$ = RuntimeHelper.requireNonNull(constants$7.lua_pushvfstring$MH, "lua_pushvfstring");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), fmt.address(), argp.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_pushfstring$MH() {
        return RuntimeHelper.requireNonNull(constants$8.lua_pushfstring$MH,"lua_pushfstring");
    }
    public static MemoryAddress lua_pushfstring ( @NotNull Addressable L,  Addressable fmt, Object... x2) {
        var mh$ = RuntimeHelper.requireNonNull(constants$8.lua_pushfstring$MH, "lua_pushfstring");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), fmt.address(), x2);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_pushcclosure$MH() {
        return RuntimeHelper.requireNonNull(constants$8.lua_pushcclosure$MH,"lua_pushcclosure");
    }
    public static void lua_pushcclosure ( @NotNull Addressable L,  Addressable fn,  int n) {
        var mh$ = RuntimeHelper.requireNonNull(constants$8.lua_pushcclosure$MH, "lua_pushcclosure");
        try {
            mh$.invokeExact(L.address(), fn.address(), n);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_pushboolean$MH() {
        return RuntimeHelper.requireNonNull(constants$8.lua_pushboolean$MH,"lua_pushboolean");
    }
    public static void lua_pushboolean ( @NotNull Addressable L,  int b) {
        var mh$ = RuntimeHelper.requireNonNull(constants$8.lua_pushboolean$MH, "lua_pushboolean");
        try {
            mh$.invokeExact(L.address(), b);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_pushlightuserdata$MH() {
        return RuntimeHelper.requireNonNull(constants$8.lua_pushlightuserdata$MH,"lua_pushlightuserdata");
    }
    public static void lua_pushlightuserdata ( @NotNull Addressable L,  Addressable p) {
        var mh$ = RuntimeHelper.requireNonNull(constants$8.lua_pushlightuserdata$MH, "lua_pushlightuserdata");
        try {
            mh$.invokeExact(L.address(), p.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_pushthread$MH() {
        return RuntimeHelper.requireNonNull(constants$8.lua_pushthread$MH,"lua_pushthread");
    }
    public static int lua_pushthread ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$8.lua_pushthread$MH, "lua_pushthread");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_getglobal$MH() {
        return RuntimeHelper.requireNonNull(constants$8.lua_getglobal$MH,"lua_getglobal");
    }
    public static int lua_getglobal ( @NotNull Addressable L,  Addressable name) {
        var mh$ = RuntimeHelper.requireNonNull(constants$8.lua_getglobal$MH, "lua_getglobal");
        try {
            return (int)mh$.invokeExact(L.address(), name.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_gettable$MH() {
        return RuntimeHelper.requireNonNull(constants$9.lua_gettable$MH,"lua_gettable");
    }
    public static int lua_gettable ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$9.lua_gettable$MH, "lua_gettable");
        try {
            return (int)mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_getfield$MH() {
        return RuntimeHelper.requireNonNull(constants$9.lua_getfield$MH,"lua_getfield");
    }
    public static int lua_getfield ( @NotNull Addressable L,  int idx,  Addressable k) {
        var mh$ = RuntimeHelper.requireNonNull(constants$9.lua_getfield$MH, "lua_getfield");
        try {
            return (int)mh$.invokeExact(L.address(), idx, k.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_geti$MH() {
        return RuntimeHelper.requireNonNull(constants$9.lua_geti$MH,"lua_geti");
    }
    public static int lua_geti ( @NotNull Addressable L,  int idx,  long n) {
        var mh$ = RuntimeHelper.requireNonNull(constants$9.lua_geti$MH, "lua_geti");
        try {
            return (int)mh$.invokeExact(L.address(), idx, n);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_rawget$MH() {
        return RuntimeHelper.requireNonNull(constants$9.lua_rawget$MH,"lua_rawget");
    }
    public static int lua_rawget ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$9.lua_rawget$MH, "lua_rawget");
        try {
            return (int)mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_rawgeti$MH() {
        return RuntimeHelper.requireNonNull(constants$9.lua_rawgeti$MH,"lua_rawgeti");
    }
    public static int lua_rawgeti ( @NotNull Addressable L,  int idx,  long n) {
        var mh$ = RuntimeHelper.requireNonNull(constants$9.lua_rawgeti$MH, "lua_rawgeti");
        try {
            return (int)mh$.invokeExact(L.address(), idx, n);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_rawgetp$MH() {
        return RuntimeHelper.requireNonNull(constants$9.lua_rawgetp$MH,"lua_rawgetp");
    }
    public static int lua_rawgetp ( @NotNull Addressable L,  int idx,  Addressable p) {
        var mh$ = RuntimeHelper.requireNonNull(constants$9.lua_rawgetp$MH, "lua_rawgetp");
        try {
            return (int)mh$.invokeExact(L.address(), idx, p.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_createtable$MH() {
        return RuntimeHelper.requireNonNull(constants$10.lua_createtable$MH,"lua_createtable");
    }
    public static void lua_createtable ( @NotNull Addressable L,  int narr,  int nrec) {
        var mh$ = RuntimeHelper.requireNonNull(constants$10.lua_createtable$MH, "lua_createtable");
        try {
            mh$.invokeExact(L.address(), narr, nrec);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_newuserdata$MH() {
        return RuntimeHelper.requireNonNull(constants$10.lua_newuserdata$MH,"lua_newuserdata");
    }
    public static MemoryAddress lua_newuserdata ( @NotNull Addressable L,  long sz) {
        var mh$ = RuntimeHelper.requireNonNull(constants$10.lua_newuserdata$MH, "lua_newuserdata");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), sz);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_getmetatable$MH() {
        return RuntimeHelper.requireNonNull(constants$10.lua_getmetatable$MH,"lua_getmetatable");
    }
    public static int lua_getmetatable ( @NotNull Addressable L,  int objindex) {
        var mh$ = RuntimeHelper.requireNonNull(constants$10.lua_getmetatable$MH, "lua_getmetatable");
        try {
            return (int)mh$.invokeExact(L.address(), objindex);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_getuservalue$MH() {
        return RuntimeHelper.requireNonNull(constants$10.lua_getuservalue$MH,"lua_getuservalue");
    }
    public static int lua_getuservalue ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$10.lua_getuservalue$MH, "lua_getuservalue");
        try {
            return (int)mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_setglobal$MH() {
        return RuntimeHelper.requireNonNull(constants$10.lua_setglobal$MH,"lua_setglobal");
    }
    public static void lua_setglobal ( @NotNull Addressable L,  Addressable name) {
        var mh$ = RuntimeHelper.requireNonNull(constants$10.lua_setglobal$MH, "lua_setglobal");
        try {
            mh$.invokeExact(L.address(), name.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_settable$MH() {
        return RuntimeHelper.requireNonNull(constants$10.lua_settable$MH,"lua_settable");
    }
    public static void lua_settable ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$10.lua_settable$MH, "lua_settable");
        try {
            mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_setfield$MH() {
        return RuntimeHelper.requireNonNull(constants$11.lua_setfield$MH,"lua_setfield");
    }
    public static void lua_setfield ( @NotNull Addressable L,  int idx,  Addressable k) {
        var mh$ = RuntimeHelper.requireNonNull(constants$11.lua_setfield$MH, "lua_setfield");
        try {
            mh$.invokeExact(L.address(), idx, k.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_seti$MH() {
        return RuntimeHelper.requireNonNull(constants$11.lua_seti$MH,"lua_seti");
    }
    public static void lua_seti ( @NotNull Addressable L,  int idx,  long n) {
        var mh$ = RuntimeHelper.requireNonNull(constants$11.lua_seti$MH, "lua_seti");
        try {
            mh$.invokeExact(L.address(), idx, n);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_rawset$MH() {
        return RuntimeHelper.requireNonNull(constants$11.lua_rawset$MH,"lua_rawset");
    }
    public static void lua_rawset ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$11.lua_rawset$MH, "lua_rawset");
        try {
            mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_rawseti$MH() {
        return RuntimeHelper.requireNonNull(constants$11.lua_rawseti$MH,"lua_rawseti");
    }
    public static void lua_rawseti ( @NotNull Addressable L,  int idx,  long n) {
        var mh$ = RuntimeHelper.requireNonNull(constants$11.lua_rawseti$MH, "lua_rawseti");
        try {
            mh$.invokeExact(L.address(), idx, n);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_rawsetp$MH() {
        return RuntimeHelper.requireNonNull(constants$11.lua_rawsetp$MH,"lua_rawsetp");
    }
    public static void lua_rawsetp ( @NotNull Addressable L,  int idx,  Addressable p) {
        var mh$ = RuntimeHelper.requireNonNull(constants$11.lua_rawsetp$MH, "lua_rawsetp");
        try {
            mh$.invokeExact(L.address(), idx, p.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_setmetatable$MH() {
        return RuntimeHelper.requireNonNull(constants$11.lua_setmetatable$MH,"lua_setmetatable");
    }
    public static int lua_setmetatable ( @NotNull Addressable L,  int objindex) {
        var mh$ = RuntimeHelper.requireNonNull(constants$11.lua_setmetatable$MH, "lua_setmetatable");
        try {
            return (int)mh$.invokeExact(L.address(), objindex);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_setuservalue$MH() {
        return RuntimeHelper.requireNonNull(constants$12.lua_setuservalue$MH,"lua_setuservalue");
    }
    public static void lua_setuservalue ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$12.lua_setuservalue$MH, "lua_setuservalue");
        try {
            mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_callk$MH() {
        return RuntimeHelper.requireNonNull(constants$12.lua_callk$MH,"lua_callk");
    }
    public static void lua_callk ( @NotNull Addressable L,  int nargs,  int nresults,  long ctx,  Addressable k) {
        var mh$ = RuntimeHelper.requireNonNull(constants$12.lua_callk$MH, "lua_callk");
        try {
            mh$.invokeExact(L.address(), nargs, nresults, ctx, k.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    // manually inserted macro translations
    public static void lua_call(@NotNull Addressable L, int n, int r) {
        lua_callk(L, n, r, 0, NULL);
    }
    // end of manually inserted macro translations
    public static MethodHandle lua_pcallk$MH() {
        return RuntimeHelper.requireNonNull(constants$12.lua_pcallk$MH,"lua_pcallk");
    }
    public static int lua_pcallk ( @NotNull Addressable L,  int nargs,  int nresults,  int errfunc,  long ctx,  Addressable k) {
        var mh$ = RuntimeHelper.requireNonNull(constants$12.lua_pcallk$MH, "lua_pcallk");
        try {
            return (int)mh$.invokeExact(L.address(), nargs, nresults, errfunc, ctx, k.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    // manually inserted macro translations
    public static int lua_pcall(@NotNull Addressable L, int n, int r, int f) {
        return lua_pcallk(L, n, r, f, 0, NULL);
    }
    // end of manually inserted macro translations
    public static MethodHandle lua_load$MH() {
        return RuntimeHelper.requireNonNull(constants$12.lua_load$MH,"lua_load");
    }
    public static int lua_load ( @NotNull Addressable L,  Addressable reader,  Addressable dt,  Addressable chunkname,  Addressable mode) {
        var mh$ = RuntimeHelper.requireNonNull(constants$12.lua_load$MH, "lua_load");
        try {
            return (int)mh$.invokeExact(L.address(), reader.address(), dt.address(), chunkname.address(), mode.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_dump$MH() {
        return RuntimeHelper.requireNonNull(constants$12.lua_dump$MH,"lua_dump");
    }
    public static int lua_dump ( @NotNull Addressable L,  Addressable writer,  Addressable data,  int strip) {
        var mh$ = RuntimeHelper.requireNonNull(constants$12.lua_dump$MH, "lua_dump");
        try {
            return (int)mh$.invokeExact(L.address(), writer.address(), data.address(), strip);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_yieldk$MH() {
        return RuntimeHelper.requireNonNull(constants$12.lua_yieldk$MH,"lua_yieldk");
    }
    public static int lua_yieldk ( @NotNull Addressable L,  int nresults,  long ctx,  Addressable k) {
        var mh$ = RuntimeHelper.requireNonNull(constants$12.lua_yieldk$MH, "lua_yieldk");
        try {
            return (int)mh$.invokeExact(L.address(), nresults, ctx, k.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_resume$MH() {
        return RuntimeHelper.requireNonNull(constants$13.lua_resume$MH,"lua_resume");
    }
    public static int lua_resume ( @NotNull Addressable L,  Addressable from,  int narg) {
        var mh$ = RuntimeHelper.requireNonNull(constants$13.lua_resume$MH, "lua_resume");
        try {
            return (int)mh$.invokeExact(L.address(), from.address(), narg);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_status$MH() {
        return RuntimeHelper.requireNonNull(constants$13.lua_status$MH,"lua_status");
    }
    public static int lua_status ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$13.lua_status$MH, "lua_status");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_isyieldable$MH() {
        return RuntimeHelper.requireNonNull(constants$13.lua_isyieldable$MH,"lua_isyieldable");
    }
    public static int lua_isyieldable ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$13.lua_isyieldable$MH, "lua_isyieldable");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    // manually inserted macro translations
    public static void lua_yield(@NotNull Addressable L, int n) {
        lua_yieldk(L, n, 0, NULL);
    }
    // end of manually inserted macro translations
    public static MethodHandle lua_gc$MH() {
        return RuntimeHelper.requireNonNull(constants$13.lua_gc$MH,"lua_gc");
    }
    public static int lua_gc ( @NotNull Addressable L,  int what,  int data) {
        var mh$ = RuntimeHelper.requireNonNull(constants$13.lua_gc$MH, "lua_gc");
        try {
            return (int)mh$.invokeExact(L.address(), what, data);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_error$MH() {
        return RuntimeHelper.requireNonNull(constants$13.lua_error$MH,"lua_error");
    }
    public static int lua_error ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$13.lua_error$MH, "lua_error");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_next$MH() {
        return RuntimeHelper.requireNonNull(constants$13.lua_next$MH,"lua_next");
    }
    public static int lua_next ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$13.lua_next$MH, "lua_next");
        try {
            return (int)mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_concat$MH() {
        return RuntimeHelper.requireNonNull(constants$14.lua_concat$MH,"lua_concat");
    }
    public static void lua_concat ( @NotNull Addressable L,  int n) {
        var mh$ = RuntimeHelper.requireNonNull(constants$14.lua_concat$MH, "lua_concat");
        try {
            mh$.invokeExact(L.address(), n);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_len$MH() {
        return RuntimeHelper.requireNonNull(constants$14.lua_len$MH,"lua_len");
    }
    public static void lua_len ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$14.lua_len$MH, "lua_len");
        try {
            mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_stringtonumber$MH() {
        return RuntimeHelper.requireNonNull(constants$14.lua_stringtonumber$MH,"lua_stringtonumber");
    }
    public static long lua_stringtonumber ( @NotNull Addressable L,  Addressable s) {
        var mh$ = RuntimeHelper.requireNonNull(constants$14.lua_stringtonumber$MH, "lua_stringtonumber");
        try {
            return (long)mh$.invokeExact(L.address(), s.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_getallocf$MH() {
        return RuntimeHelper.requireNonNull(constants$14.lua_getallocf$MH,"lua_getallocf");
    }
    public static MemoryAddress lua_getallocf ( @NotNull Addressable L,  Addressable ud) {
        var mh$ = RuntimeHelper.requireNonNull(constants$14.lua_getallocf$MH, "lua_getallocf");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), ud.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_setallocf$MH() {
        return RuntimeHelper.requireNonNull(constants$14.lua_setallocf$MH,"lua_setallocf");
    }
    public static void lua_setallocf ( @NotNull Addressable L,  Addressable f,  Addressable ud) {
        var mh$ = RuntimeHelper.requireNonNull(constants$14.lua_setallocf$MH, "lua_setallocf");
        try {
            mh$.invokeExact(L.address(), f.address(), ud.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    // manually inserted macro translations
    // some useful macros
    public static Addressable lua_getextraspace(@NotNull Addressable L) {
        return L.address().addOffset(-LUA_EXTRASPACE());
    }
    public static double lua_tonumber(@NotNull Addressable L, int i) {
        return lua_tonumberx(L, i, NULL);
    }
    public static long lua_tointeger(@NotNull Addressable L, int i) {
        return lua_tointegerx(L, i, NULL);
    }
    public static void lua_pop(@NotNull Addressable L, int n) {
        lua_settop(L, -n-1);
    }
    public static void lua_newtable(@NotNull Addressable L) {
        lua_createtable(L, 0, 0);
    }
    public static void lua_register(@NotNull Addressable L, Addressable n, Addressable f) {
        lua_pushcfunction(L, f);
        lua_setglobal(L, f);
    }
    public static void lua_pushcfunction(@NotNull Addressable L, Addressable f) {
        lua_pushcclosure(L, f, 0);
    }
    public static boolean lua_isfunction(@NotNull Addressable L, int n) {
        return lua_type(L, n) == LUA_TFUNCTION();
    }
    public static boolean lua_istable(@NotNull Addressable L, int n) {
        return lua_type(L, n) == LUA_TTABLE();
    }
    public static boolean lua_islightuserdata(@NotNull Addressable L, int n) {
        return lua_type(L, n) == LUA_TLIGHTUSERDATA();
    }
    public static boolean lua_isnil(@NotNull Addressable L, int n) {
        return lua_type(L, n) == LUA_TNIL();
    }
    public static boolean lua_isboolean(@NotNull Addressable L, int n) {
        return lua_type(L, n) == LUA_TBOOLEAN();
    }
    public static boolean lua_isthread(@NotNull Addressable L, int n) {
        return lua_type(L, n) == LUA_TTHREAD();
    }
    public static boolean lua_isnone(@NotNull Addressable L, int n) {
        return lua_type(L, n) == LUA_TNONE();
    }
    public static boolean lua_isnoneornil(@NotNull Addressable L, int n) {
        return lua_type(L, n) <= 0;
    }
    public static void lua_pushliteral(@NotNull Addressable L, String s) {
        try (ResourceScope scope = ResourceScope.newConfinedScope()) {
            lua_pushstring(L, CLinker.toCString(s, scope));
        }
    }
    public static void lua_pushglobaltable(@NotNull Addressable L) {
        lua_rawgeti(L, LUA_REGISTRYINDEX(), LUA_RIDX_GLOBALS());
    }
    public static MemoryAddress lua_tostring(@NotNull Addressable L, int i) {
        return lua_tolstring(L, i, NULL);
    }
    public static void lua_insert(@NotNull Addressable L, int idx) {
        lua_rotate(L, idx, 1);
    }
    public static void lua_remove(@NotNull Addressable L, int idx) {
        lua_rotate(L, idx, -1);
        lua_pop(L, 1);
    }
    public static void lua_replace(@NotNull Addressable L, int idx) {
        lua_copy(L, -1, idx);
        lua_pop(L, 1);
    }
    // end of manually inserted macro translations
    public static MethodHandle lua_getstack$MH() {
        return RuntimeHelper.requireNonNull(constants$15.lua_getstack$MH,"lua_getstack");
    }
    public static int lua_getstack ( @NotNull Addressable L,  int level,  Addressable ar) {
        var mh$ = RuntimeHelper.requireNonNull(constants$15.lua_getstack$MH, "lua_getstack");
        try {
            return (int)mh$.invokeExact(L.address(), level, ar.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_getinfo$MH() {
        return RuntimeHelper.requireNonNull(constants$15.lua_getinfo$MH,"lua_getinfo");
    }
    public static int lua_getinfo ( @NotNull Addressable L,  Addressable what,  Addressable ar) {
        var mh$ = RuntimeHelper.requireNonNull(constants$15.lua_getinfo$MH, "lua_getinfo");
        try {
            return (int)mh$.invokeExact(L.address(), what.address(), ar.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_getlocal$MH() {
        return RuntimeHelper.requireNonNull(constants$15.lua_getlocal$MH,"lua_getlocal");
    }
    public static MemoryAddress lua_getlocal ( @NotNull Addressable L,  Addressable ar,  int n) {
        var mh$ = RuntimeHelper.requireNonNull(constants$15.lua_getlocal$MH, "lua_getlocal");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), ar.address(), n);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_setlocal$MH() {
        return RuntimeHelper.requireNonNull(constants$15.lua_setlocal$MH,"lua_setlocal");
    }
    public static MemoryAddress lua_setlocal ( @NotNull Addressable L,  Addressable ar,  int n) {
        var mh$ = RuntimeHelper.requireNonNull(constants$15.lua_setlocal$MH, "lua_setlocal");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), ar.address(), n);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_getupvalue$MH() {
        return RuntimeHelper.requireNonNull(constants$15.lua_getupvalue$MH,"lua_getupvalue");
    }
    public static MemoryAddress lua_getupvalue ( @NotNull Addressable L,  int funcindex,  int n) {
        var mh$ = RuntimeHelper.requireNonNull(constants$15.lua_getupvalue$MH, "lua_getupvalue");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), funcindex, n);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_setupvalue$MH() {
        return RuntimeHelper.requireNonNull(constants$16.lua_setupvalue$MH,"lua_setupvalue");
    }
    public static MemoryAddress lua_setupvalue ( @NotNull Addressable L,  int funcindex,  int n) {
        var mh$ = RuntimeHelper.requireNonNull(constants$16.lua_setupvalue$MH, "lua_setupvalue");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), funcindex, n);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_upvalueid$MH() {
        return RuntimeHelper.requireNonNull(constants$16.lua_upvalueid$MH,"lua_upvalueid");
    }
    public static MemoryAddress lua_upvalueid ( @NotNull Addressable L,  int fidx,  int n) {
        var mh$ = RuntimeHelper.requireNonNull(constants$16.lua_upvalueid$MH, "lua_upvalueid");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), fidx, n);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_upvaluejoin$MH() {
        return RuntimeHelper.requireNonNull(constants$16.lua_upvaluejoin$MH,"lua_upvaluejoin");
    }
    public static void lua_upvaluejoin ( @NotNull Addressable L,  int fidx1,  int n1,  int fidx2,  int n2) {
        var mh$ = RuntimeHelper.requireNonNull(constants$16.lua_upvaluejoin$MH, "lua_upvaluejoin");
        try {
            mh$.invokeExact(L.address(), fidx1, n1, fidx2, n2);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_sethook$MH() {
        return RuntimeHelper.requireNonNull(constants$16.lua_sethook$MH,"lua_sethook");
    }
    public static void lua_sethook ( @NotNull Addressable L,  Addressable func,  int mask,  int count) {
        var mh$ = RuntimeHelper.requireNonNull(constants$16.lua_sethook$MH, "lua_sethook");
        try {
            mh$.invokeExact(L.address(), func.address(), mask, count);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_gethook$MH() {
        return RuntimeHelper.requireNonNull(constants$16.lua_gethook$MH,"lua_gethook");
    }
    public static MemoryAddress lua_gethook ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$16.lua_gethook$MH, "lua_gethook");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_gethookmask$MH() {
        return RuntimeHelper.requireNonNull(constants$16.lua_gethookmask$MH,"lua_gethookmask");
    }
    public static int lua_gethookmask ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$16.lua_gethookmask$MH, "lua_gethookmask");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle lua_gethookcount$MH() {
        return RuntimeHelper.requireNonNull(constants$17.lua_gethookcount$MH,"lua_gethookcount");
    }
    public static int lua_gethookcount ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$17.lua_gethookcount$MH, "lua_gethookcount");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaopen_base$MH() {
        return RuntimeHelper.requireNonNull(constants$17.luaopen_base$MH,"luaopen_base");
    }
    public static int luaopen_base ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$17.luaopen_base$MH, "luaopen_base");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaopen_coroutine$MH() {
        return RuntimeHelper.requireNonNull(constants$17.luaopen_coroutine$MH,"luaopen_coroutine");
    }
    public static int luaopen_coroutine ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$17.luaopen_coroutine$MH, "luaopen_coroutine");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaopen_table$MH() {
        return RuntimeHelper.requireNonNull(constants$17.luaopen_table$MH,"luaopen_table");
    }
    public static int luaopen_table ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$17.luaopen_table$MH, "luaopen_table");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaopen_io$MH() {
        return RuntimeHelper.requireNonNull(constants$17.luaopen_io$MH,"luaopen_io");
    }
    public static int luaopen_io ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$17.luaopen_io$MH, "luaopen_io");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaopen_os$MH() {
        return RuntimeHelper.requireNonNull(constants$17.luaopen_os$MH,"luaopen_os");
    }
    public static int luaopen_os ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$17.luaopen_os$MH, "luaopen_os");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaopen_string$MH() {
        return RuntimeHelper.requireNonNull(constants$18.luaopen_string$MH,"luaopen_string");
    }
    public static int luaopen_string ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$18.luaopen_string$MH, "luaopen_string");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaopen_utf8$MH() {
        return RuntimeHelper.requireNonNull(constants$18.luaopen_utf8$MH,"luaopen_utf8");
    }
    public static int luaopen_utf8 ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$18.luaopen_utf8$MH, "luaopen_utf8");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaopen_bit32$MH() {
        return RuntimeHelper.requireNonNull(constants$18.luaopen_bit32$MH,"luaopen_bit32");
    }
    public static int luaopen_bit32 ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$18.luaopen_bit32$MH, "luaopen_bit32");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaopen_math$MH() {
        return RuntimeHelper.requireNonNull(constants$18.luaopen_math$MH,"luaopen_math");
    }
    public static int luaopen_math ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$18.luaopen_math$MH, "luaopen_math");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaopen_debug$MH() {
        return RuntimeHelper.requireNonNull(constants$18.luaopen_debug$MH,"luaopen_debug");
    }
    public static int luaopen_debug ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$18.luaopen_debug$MH, "luaopen_debug");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaopen_package$MH() {
        return RuntimeHelper.requireNonNull(constants$18.luaopen_package$MH,"luaopen_package");
    }
    public static int luaopen_package ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$18.luaopen_package$MH, "luaopen_package");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaopen_eris$MH() {
        return RuntimeHelper.requireNonNull(constants$19.luaopen_eris$MH,"luaopen_eris");
    }
    public static int luaopen_eris ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$19.luaopen_eris$MH, "luaopen_eris");
        try {
            return (int)mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_openlibs$MH() {
        return RuntimeHelper.requireNonNull(constants$19.luaL_openlibs$MH,"luaL_openlibs");
    }
    public static void luaL_openlibs ( @NotNull Addressable L) {
        var mh$ = RuntimeHelper.requireNonNull(constants$19.luaL_openlibs$MH, "luaL_openlibs");
        try {
            mh$.invokeExact(L.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_checkversion_$MH() {
        return RuntimeHelper.requireNonNull(constants$19.luaL_checkversion_$MH,"luaL_checkversion_");
    }
    public static void luaL_checkversion_ ( @NotNull Addressable L,  double ver,  long sz) {
        var mh$ = RuntimeHelper.requireNonNull(constants$19.luaL_checkversion_$MH, "luaL_checkversion_");
        try {
            mh$.invokeExact(L.address(), ver, sz);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    // manually inserted macro translations
    public static void luaL_checkversion(@NotNull Addressable L) {
        luaL_checkversion_(L, LUA_VERSION_NUM(), LUAL_NUMSIZES());
    }
    // end of manually inserted macro translations
    public static MethodHandle luaL_getmetafield$MH() {
        return RuntimeHelper.requireNonNull(constants$19.luaL_getmetafield$MH,"luaL_getmetafield");
    }
    public static int luaL_getmetafield ( @NotNull Addressable L,  int obj,  Addressable e) {
        var mh$ = RuntimeHelper.requireNonNull(constants$19.luaL_getmetafield$MH, "luaL_getmetafield");
        try {
            return (int)mh$.invokeExact(L.address(), obj, e.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_callmeta$MH() {
        return RuntimeHelper.requireNonNull(constants$19.luaL_callmeta$MH,"luaL_callmeta");
    }
    public static int luaL_callmeta ( @NotNull Addressable L,  int obj,  Addressable e) {
        var mh$ = RuntimeHelper.requireNonNull(constants$19.luaL_callmeta$MH, "luaL_callmeta");
        try {
            return (int)mh$.invokeExact(L.address(), obj, e.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_tolstring$MH() {
        return RuntimeHelper.requireNonNull(constants$19.luaL_tolstring$MH,"luaL_tolstring");
    }
    public static MemoryAddress luaL_tolstring ( @NotNull Addressable L,  int idx,  Addressable len) {
        var mh$ = RuntimeHelper.requireNonNull(constants$19.luaL_tolstring$MH, "luaL_tolstring");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), idx, len.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_argerror$MH() {
        return RuntimeHelper.requireNonNull(constants$20.luaL_argerror$MH,"luaL_argerror");
    }
    public static int luaL_argerror ( @NotNull Addressable L,  int arg,  Addressable extramsg) {
        var mh$ = RuntimeHelper.requireNonNull(constants$20.luaL_argerror$MH, "luaL_argerror");
        try {
            return (int)mh$.invokeExact(L.address(), arg, extramsg.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_checklstring$MH() {
        return RuntimeHelper.requireNonNull(constants$20.luaL_checklstring$MH,"luaL_checklstring");
    }
    public static MemoryAddress luaL_checklstring ( @NotNull Addressable L,  int arg,  Addressable l) {
        var mh$ = RuntimeHelper.requireNonNull(constants$20.luaL_checklstring$MH, "luaL_checklstring");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), arg, l.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_optlstring$MH() {
        return RuntimeHelper.requireNonNull(constants$20.luaL_optlstring$MH,"luaL_optlstring");
    }
    public static MemoryAddress luaL_optlstring ( @NotNull Addressable L,  int arg,  Addressable def,  Addressable l) {
        var mh$ = RuntimeHelper.requireNonNull(constants$20.luaL_optlstring$MH, "luaL_optlstring");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), arg, def.address(), l.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_checknumber$MH() {
        return RuntimeHelper.requireNonNull(constants$20.luaL_checknumber$MH,"luaL_checknumber");
    }
    public static double luaL_checknumber ( @NotNull Addressable L,  int arg) {
        var mh$ = RuntimeHelper.requireNonNull(constants$20.luaL_checknumber$MH, "luaL_checknumber");
        try {
            return (double)mh$.invokeExact(L.address(), arg);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_optnumber$MH() {
        return RuntimeHelper.requireNonNull(constants$20.luaL_optnumber$MH,"luaL_optnumber");
    }
    public static double luaL_optnumber ( @NotNull Addressable L,  int arg,  double def) {
        var mh$ = RuntimeHelper.requireNonNull(constants$20.luaL_optnumber$MH, "luaL_optnumber");
        try {
            return (double)mh$.invokeExact(L.address(), arg, def);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_checkinteger$MH() {
        return RuntimeHelper.requireNonNull(constants$20.luaL_checkinteger$MH,"luaL_checkinteger");
    }
    public static long luaL_checkinteger ( @NotNull Addressable L,  int arg) {
        var mh$ = RuntimeHelper.requireNonNull(constants$20.luaL_checkinteger$MH, "luaL_checkinteger");
        try {
            return (long)mh$.invokeExact(L.address(), arg);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_optinteger$MH() {
        return RuntimeHelper.requireNonNull(constants$21.luaL_optinteger$MH,"luaL_optinteger");
    }
    public static long luaL_optinteger ( @NotNull Addressable L,  int arg,  long def) {
        var mh$ = RuntimeHelper.requireNonNull(constants$21.luaL_optinteger$MH, "luaL_optinteger");
        try {
            return (long)mh$.invokeExact(L.address(), arg, def);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_checkstack$MH() {
        return RuntimeHelper.requireNonNull(constants$21.luaL_checkstack$MH,"luaL_checkstack");
    }
    public static void luaL_checkstack ( @NotNull Addressable L,  int sz,  Addressable msg) {
        var mh$ = RuntimeHelper.requireNonNull(constants$21.luaL_checkstack$MH, "luaL_checkstack");
        try {
            mh$.invokeExact(L.address(), sz, msg.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_checktype$MH() {
        return RuntimeHelper.requireNonNull(constants$21.luaL_checktype$MH,"luaL_checktype");
    }
    public static void luaL_checktype ( @NotNull Addressable L,  int arg,  int t) {
        var mh$ = RuntimeHelper.requireNonNull(constants$21.luaL_checktype$MH, "luaL_checktype");
        try {
            mh$.invokeExact(L.address(), arg, t);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_checkany$MH() {
        return RuntimeHelper.requireNonNull(constants$21.luaL_checkany$MH,"luaL_checkany");
    }
    public static void luaL_checkany ( @NotNull Addressable L,  int arg) {
        var mh$ = RuntimeHelper.requireNonNull(constants$21.luaL_checkany$MH, "luaL_checkany");
        try {
            mh$.invokeExact(L.address(), arg);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_newmetatable$MH() {
        return RuntimeHelper.requireNonNull(constants$21.luaL_newmetatable$MH,"luaL_newmetatable");
    }
    public static int luaL_newmetatable ( @NotNull Addressable L,  Addressable tname) {
        var mh$ = RuntimeHelper.requireNonNull(constants$21.luaL_newmetatable$MH, "luaL_newmetatable");
        try {
            return (int)mh$.invokeExact(L.address(), tname.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_setmetatable$MH() {
        return RuntimeHelper.requireNonNull(constants$21.luaL_setmetatable$MH,"luaL_setmetatable");
    }
    public static void luaL_setmetatable ( @NotNull Addressable L,  Addressable tname) {
        var mh$ = RuntimeHelper.requireNonNull(constants$21.luaL_setmetatable$MH, "luaL_setmetatable");
        try {
            mh$.invokeExact(L.address(), tname.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_testudata$MH() {
        return RuntimeHelper.requireNonNull(constants$22.luaL_testudata$MH,"luaL_testudata");
    }
    public static MemoryAddress luaL_testudata ( @NotNull Addressable L,  int ud,  Addressable tname) {
        var mh$ = RuntimeHelper.requireNonNull(constants$22.luaL_testudata$MH, "luaL_testudata");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), ud, tname.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_checkudata$MH() {
        return RuntimeHelper.requireNonNull(constants$22.luaL_checkudata$MH,"luaL_checkudata");
    }
    public static MemoryAddress luaL_checkudata ( @NotNull Addressable L,  int ud,  Addressable tname) {
        var mh$ = RuntimeHelper.requireNonNull(constants$22.luaL_checkudata$MH, "luaL_checkudata");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), ud, tname.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_where$MH() {
        return RuntimeHelper.requireNonNull(constants$22.luaL_where$MH,"luaL_where");
    }
    public static void luaL_where ( @NotNull Addressable L,  int lvl) {
        var mh$ = RuntimeHelper.requireNonNull(constants$22.luaL_where$MH, "luaL_where");
        try {
            mh$.invokeExact(L.address(), lvl);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_error$MH() {
        return RuntimeHelper.requireNonNull(constants$22.luaL_error$MH,"luaL_error");
    }
    public static int luaL_error ( @NotNull Addressable L,  Addressable fmt, Object... x2) {
        var mh$ = RuntimeHelper.requireNonNull(constants$22.luaL_error$MH, "luaL_error");
        try {
            return (int)mh$.invokeExact(L.address(), fmt.address(), x2);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_checkoption$MH() {
        return RuntimeHelper.requireNonNull(constants$22.luaL_checkoption$MH,"luaL_checkoption");
    }
    public static int luaL_checkoption ( @NotNull Addressable L,  int arg,  Addressable def,  Addressable lst) {
        var mh$ = RuntimeHelper.requireNonNull(constants$22.luaL_checkoption$MH, "luaL_checkoption");
        try {
            return (int)mh$.invokeExact(L.address(), arg, def.address(), lst.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_fileresult$MH() {
        return RuntimeHelper.requireNonNull(constants$22.luaL_fileresult$MH,"luaL_fileresult");
    }
    public static int luaL_fileresult ( @NotNull Addressable L,  int stat,  Addressable fname) {
        var mh$ = RuntimeHelper.requireNonNull(constants$22.luaL_fileresult$MH, "luaL_fileresult");
        try {
            return (int)mh$.invokeExact(L.address(), stat, fname.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_execresult$MH() {
        return RuntimeHelper.requireNonNull(constants$23.luaL_execresult$MH,"luaL_execresult");
    }
    public static int luaL_execresult ( @NotNull Addressable L,  int stat) {
        var mh$ = RuntimeHelper.requireNonNull(constants$23.luaL_execresult$MH, "luaL_execresult");
        try {
            return (int)mh$.invokeExact(L.address(), stat);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_ref$MH() {
        return RuntimeHelper.requireNonNull(constants$23.luaL_ref$MH,"luaL_ref");
    }
    public static int luaL_ref ( @NotNull Addressable L,  int t) {
        var mh$ = RuntimeHelper.requireNonNull(constants$23.luaL_ref$MH, "luaL_ref");
        try {
            return (int)mh$.invokeExact(L.address(), t);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_unref$MH() {
        return RuntimeHelper.requireNonNull(constants$23.luaL_unref$MH,"luaL_unref");
    }
    public static void luaL_unref ( @NotNull Addressable L,  int t,  int ref) {
        var mh$ = RuntimeHelper.requireNonNull(constants$23.luaL_unref$MH, "luaL_unref");
        try {
            mh$.invokeExact(L.address(), t, ref);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_loadfilex$MH() {
        return RuntimeHelper.requireNonNull(constants$23.luaL_loadfilex$MH,"luaL_loadfilex");
    }
    public static int luaL_loadfilex ( @NotNull Addressable L,  Addressable filename,  Addressable mode) {
        var mh$ = RuntimeHelper.requireNonNull(constants$23.luaL_loadfilex$MH, "luaL_loadfilex");
        try {
            return (int)mh$.invokeExact(L.address(), filename.address(), mode.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    // manually inserted macro translations
    public static int luaL_loadfile(@NotNull Addressable L, Addressable f) {
        return luaL_loadfilex(L, f, NULL);
    }
    // end of manually inserted macro translations
    public static MethodHandle luaL_loadbufferx$MH() {
        return RuntimeHelper.requireNonNull(constants$23.luaL_loadbufferx$MH,"luaL_loadbufferx");
    }
    public static int luaL_loadbufferx ( @NotNull Addressable L,  Addressable buff,  long sz,  Addressable name,  Addressable mode) {
        var mh$ = RuntimeHelper.requireNonNull(constants$23.luaL_loadbufferx$MH, "luaL_loadbufferx");
        try {
            return (int)mh$.invokeExact(L.address(), buff.address(), sz, name.address(), mode.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_loadstring$MH() {
        return RuntimeHelper.requireNonNull(constants$23.luaL_loadstring$MH,"luaL_loadstring");
    }
    public static int luaL_loadstring ( @NotNull Addressable L,  Addressable s) {
        var mh$ = RuntimeHelper.requireNonNull(constants$23.luaL_loadstring$MH, "luaL_loadstring");
        try {
            return (int)mh$.invokeExact(L.address(), s.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_newstate$MH() {
        return RuntimeHelper.requireNonNull(constants$24.luaL_newstate$MH,"luaL_newstate");
    }
    public static MemoryAddress luaL_newstate () {
        var mh$ = RuntimeHelper.requireNonNull(constants$24.luaL_newstate$MH, "luaL_newstate");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_len$MH() {
        return RuntimeHelper.requireNonNull(constants$24.luaL_len$MH,"luaL_len");
    }
    public static long luaL_len ( @NotNull Addressable L,  int idx) {
        var mh$ = RuntimeHelper.requireNonNull(constants$24.luaL_len$MH, "luaL_len");
        try {
            return (long)mh$.invokeExact(L.address(), idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_gsub$MH() {
        return RuntimeHelper.requireNonNull(constants$24.luaL_gsub$MH,"luaL_gsub");
    }
    public static MemoryAddress luaL_gsub ( @NotNull Addressable L,  Addressable s,  Addressable p,  Addressable r) {
        var mh$ = RuntimeHelper.requireNonNull(constants$24.luaL_gsub$MH, "luaL_gsub");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), s.address(), p.address(), r.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_setfuncs$MH() {
        return RuntimeHelper.requireNonNull(constants$24.luaL_setfuncs$MH,"luaL_setfuncs");
    }
    public static void luaL_setfuncs ( @NotNull Addressable L,  Addressable l,  int nup) {
        var mh$ = RuntimeHelper.requireNonNull(constants$24.luaL_setfuncs$MH, "luaL_setfuncs");
        try {
            mh$.invokeExact(L.address(), l.address(), nup);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_getsubtable$MH() {
        return RuntimeHelper.requireNonNull(constants$24.luaL_getsubtable$MH,"luaL_getsubtable");
    }
    public static int luaL_getsubtable ( @NotNull Addressable L,  int idx,  Addressable fname) {
        var mh$ = RuntimeHelper.requireNonNull(constants$24.luaL_getsubtable$MH, "luaL_getsubtable");
        try {
            return (int)mh$.invokeExact(L.address(), idx, fname.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_traceback$MH() {
        return RuntimeHelper.requireNonNull(constants$24.luaL_traceback$MH,"luaL_traceback");
    }
    public static void luaL_traceback ( @NotNull Addressable L,  Addressable L1,  Addressable msg,  int level) {
        var mh$ = RuntimeHelper.requireNonNull(constants$24.luaL_traceback$MH, "luaL_traceback");
        try {
            mh$.invokeExact(L.address(), L1.address(), msg.address(), level);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_requiref$MH() {
        return RuntimeHelper.requireNonNull(constants$25.luaL_requiref$MH,"luaL_requiref");
    }
    public static void luaL_requiref ( @NotNull Addressable L,  Addressable modname,  Addressable openf,  int glb) {
        var mh$ = RuntimeHelper.requireNonNull(constants$25.luaL_requiref$MH, "luaL_requiref");
        try {
            mh$.invokeExact(L.address(), modname.address(), openf.address(), glb);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    // manually inserted macro translations
    // some useful macros
    // TODO: luaL_newlibtable
    // TODO: luaL_newlib
    public static void luaL_argcheck(@NotNull Addressable L, boolean cond, int arg, Addressable extramsg) {
        if (!cond)
            luaL_argerror(L, arg, extramsg);
    }
    public static MemoryAddress luaL_checkstring(@NotNull Addressable L, int n) {
        return luaL_checklstring(L, n, NULL);
    }
    public static MemoryAddress luaL_optstring(@NotNull Addressable L, int n, Addressable d) {
        return luaL_optlstring(L, n, d, NULL);
    }
    public static MemoryAddress luaL_typename(@NotNull Addressable L, int i) {
        return lua_typename(L, lua_type(L, i));
    }
    public static int luaL_dofile(@NotNull Addressable L, Addressable fn) {
        int err = luaL_loadfile(L, fn);
        if (err == 0)
            err = lua_pcall(L, 0, LUA_MULTRET(), 0);
        return err;
    }
    public static int luaL_dostring(@NotNull Addressable L, Addressable s) {
        int err = luaL_loadstring(L, s);
        if (err == 0)
            err = lua_pcall(L, 0, LUA_MULTRET(), 0);
        return err;
    }
    public static int luaL_getmetatable(@NotNull Addressable L, Addressable n) {
        return lua_getfield(L, LUA_REGISTRYINDEX(), n);
    }
    // TODO: lua_opt (function argument)
    public static int luaL_loadbuffer(@NotNull Addressable L, Addressable s, long sz, Addressable n) {
        return luaL_loadbufferx(L,s,sz,n,NULL);
    }
    // Generic Buffer manipulation
    public static void luaL_addchar(MemorySegment B, byte c) {
        if (luaL_Buffer.n$get(B) >= luaL_Buffer.size$get(B))
            luaL_prepbuffsize((B), 1);
        MemoryAccess.setByte(luaL_Buffer.b$get(B).addOffset((long)luaL_Buffer.n$VH().getAndAdd(B, 1L)).asSegment(1, ResourceScope.globalScope()), c);
    }
    public static void luaL_addsize(MemorySegment B, long s) {
        luaL_Buffer.n$set(B, luaL_Buffer.n$get(B)+s);
    }
    // end of manually inserted macro translations
    public static MethodHandle luaL_buffinit$MH() {
        return RuntimeHelper.requireNonNull(constants$25.luaL_buffinit$MH,"luaL_buffinit");
    }
    public static void luaL_buffinit ( @NotNull Addressable L,  Addressable B) {
        var mh$ = RuntimeHelper.requireNonNull(constants$25.luaL_buffinit$MH, "luaL_buffinit");
        try {
            mh$.invokeExact(L.address(), B.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_prepbuffsize$MH() {
        return RuntimeHelper.requireNonNull(constants$25.luaL_prepbuffsize$MH,"luaL_prepbuffsize");
    }
    public static MemoryAddress luaL_prepbuffsize ( Addressable B,  long sz) {
        var mh$ = RuntimeHelper.requireNonNull(constants$25.luaL_prepbuffsize$MH, "luaL_prepbuffsize");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(B.address(), sz);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_addlstring$MH() {
        return RuntimeHelper.requireNonNull(constants$25.luaL_addlstring$MH,"luaL_addlstring");
    }
    public static void luaL_addlstring ( Addressable B,  Addressable s,  long l) {
        var mh$ = RuntimeHelper.requireNonNull(constants$25.luaL_addlstring$MH, "luaL_addlstring");
        try {
            mh$.invokeExact(B.address(), s.address(), l);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_addstring$MH() {
        return RuntimeHelper.requireNonNull(constants$25.luaL_addstring$MH,"luaL_addstring");
    }
    public static void luaL_addstring ( Addressable B,  Addressable s) {
        var mh$ = RuntimeHelper.requireNonNull(constants$25.luaL_addstring$MH, "luaL_addstring");
        try {
            mh$.invokeExact(B.address(), s.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_addvalue$MH() {
        return RuntimeHelper.requireNonNull(constants$25.luaL_addvalue$MH,"luaL_addvalue");
    }
    public static void luaL_addvalue ( Addressable B) {
        var mh$ = RuntimeHelper.requireNonNull(constants$25.luaL_addvalue$MH, "luaL_addvalue");
        try {
            mh$.invokeExact(B.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_pushresult$MH() {
        return RuntimeHelper.requireNonNull(constants$26.luaL_pushresult$MH,"luaL_pushresult");
    }
    public static void luaL_pushresult ( Addressable B) {
        var mh$ = RuntimeHelper.requireNonNull(constants$26.luaL_pushresult$MH, "luaL_pushresult");
        try {
            mh$.invokeExact(B.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_pushresultsize$MH() {
        return RuntimeHelper.requireNonNull(constants$26.luaL_pushresultsize$MH,"luaL_pushresultsize");
    }
    public static void luaL_pushresultsize ( Addressable B,  long sz) {
        var mh$ = RuntimeHelper.requireNonNull(constants$26.luaL_pushresultsize$MH, "luaL_pushresultsize");
        try {
            mh$.invokeExact(B.address(), sz);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle luaL_buffinitsize$MH() {
        return RuntimeHelper.requireNonNull(constants$26.luaL_buffinitsize$MH,"luaL_buffinitsize");
    }
    public static MemoryAddress luaL_buffinitsize ( @NotNull Addressable L,  Addressable B,  long sz) {
        var mh$ = RuntimeHelper.requireNonNull(constants$26.luaL_buffinitsize$MH, "luaL_buffinitsize");
        try {
            return (jdk.incubator.foreign.MemoryAddress)mh$.invokeExact(L.address(), B.address(), sz);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    // manually inserted macro translations
    public static MemoryAddress luaL_prepbuffer(Addressable B) {
        return luaL_prepbuffsize(B, LUAL_BUFFERSIZE());
    }
    // end of manually inserted macro translations
    public static MethodHandle eris_dump$MH() {
        return RuntimeHelper.requireNonNull(constants$26.eris_dump$MH,"eris_dump");
    }
    public static void eris_dump ( @NotNull Addressable L,  Addressable writer,  Addressable ud) {
        var mh$ = RuntimeHelper.requireNonNull(constants$26.eris_dump$MH, "eris_dump");
        try {
            mh$.invokeExact(L.address(), writer.address(), ud.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle eris_undump$MH() {
        return RuntimeHelper.requireNonNull(constants$26.eris_undump$MH,"eris_undump");
    }
    public static void eris_undump ( @NotNull Addressable L,  Addressable reader,  Addressable ud) {
        var mh$ = RuntimeHelper.requireNonNull(constants$26.eris_undump$MH, "eris_undump");
        try {
            mh$.invokeExact(L.address(), reader.address(), ud.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle eris_persist$MH() {
        return RuntimeHelper.requireNonNull(constants$26.eris_persist$MH,"eris_persist");
    }
    public static void eris_persist ( @NotNull Addressable L,  int perms,  int value) {
        var mh$ = RuntimeHelper.requireNonNull(constants$26.eris_persist$MH, "eris_persist");
        try {
            mh$.invokeExact(L.address(), perms, value);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle eris_unpersist$MH() {
        return RuntimeHelper.requireNonNull(constants$27.eris_unpersist$MH,"eris_unpersist");
    }
    public static void eris_unpersist ( @NotNull Addressable L,  int perms,  int value) {
        var mh$ = RuntimeHelper.requireNonNull(constants$27.eris_unpersist$MH, "eris_unpersist");
        try {
            mh$.invokeExact(L.address(), perms, value);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle eris_get_setting$MH() {
        return RuntimeHelper.requireNonNull(constants$27.eris_get_setting$MH,"eris_get_setting");
    }
    public static void eris_get_setting ( @NotNull Addressable L,  Addressable name) {
        var mh$ = RuntimeHelper.requireNonNull(constants$27.eris_get_setting$MH, "eris_get_setting");
        try {
            mh$.invokeExact(L.address(), name.address());
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle eris_set_setting$MH() {
        return RuntimeHelper.requireNonNull(constants$27.eris_set_setting$MH,"eris_set_setting");
    }
    public static void eris_set_setting ( @NotNull Addressable L,  Addressable name,  int value) {
        var mh$ = RuntimeHelper.requireNonNull(constants$27.eris_set_setting$MH, "eris_set_setting");
        try {
            mh$.invokeExact(L.address(), name.address(), value);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static int LUA_INT_TYPE() {
        return (int)3L;
    }
    public static int LUA_FLOAT_TYPE() {
        return (int)2L;
    }
    public static MemorySegment LUA_PATH_SEP() {
        return constants$27.LUA_PATH_SEP$SEGMENT;
    }
    public static MemorySegment LUA_PATH_MARK() {
        return constants$27.LUA_PATH_MARK$SEGMENT;
    }
    public static MemorySegment LUA_VDIR() {
        return constants$27.LUA_VDIR$SEGMENT;
    }
    public static MemorySegment LUA_NUMBER_FRMLEN() {
        return constants$28.LUA_NUMBER_FRMLEN$SEGMENT;
    }
    public static MemorySegment LUA_NUMBER_FMT() {
        return constants$28.LUA_NUMBER_FMT$SEGMENT;
    }
    public static MemorySegment LUA_INTEGER_FMT() {
        return constants$28.LUA_INTEGER_FMT$SEGMENT;
    }
    public static MemorySegment LUA_INTEGER_FRMLEN() {
        return constants$28.LUA_INTEGER_FRMLEN$SEGMENT;
    }
    public static long LUA_MAXINTEGER() {
        return 9223372036854775807L;
    }
    public static long LUA_MININTEGER() {
        return -9223372036854775808L;
    }
    public static long LUA_EXTRASPACE() {
        return 8L;
    }
    public static int LUAL_BUFFERSIZE() {
        return (int)8192L;
    }
    public static MemorySegment LUA_QS() {
        return constants$28.LUA_QS$SEGMENT;
    }
    public static MemorySegment LUA_VERSION_MAJOR() {
        return constants$28.LUA_VERSION_MAJOR$SEGMENT;
    }
    public static MemorySegment LUA_VERSION_MINOR() {
        return constants$29.LUA_VERSION_MINOR$SEGMENT;
    }
    public static MemorySegment LUA_VERSION_RELEASE() {
        return constants$29.LUA_VERSION_RELEASE$SEGMENT;
    }
    public static MemorySegment LUA_VERSION() {
        return constants$29.LUA_VERSION$SEGMENT;
    }
    public static MemorySegment LUA_RELEASE() {
        return constants$29.LUA_RELEASE$SEGMENT;
    }
    public static MemorySegment LUA_COPYRIGHT() {
        return constants$29.LUA_COPYRIGHT$SEGMENT;
    }
    public static MemorySegment LUA_AUTHORS() {
        return constants$29.LUA_AUTHORS$SEGMENT;
    }
    public static MemorySegment LUA_SIGNATURE() {
        return constants$30.LUA_SIGNATURE$SEGMENT;
    }
    public static int LUA_MULTRET() {
        return (int)-1L;
    }
    public static int LUA_REGISTRYINDEX() {
        return (int)-1001000L;
    }
    public static int LUA_TNONE() {
        return (int)-1L;
    }
    public static int LUA_RIDX_LAST() {
        return (int)2L;
    }
    public static int LUA_MASKCALL() {
        return (int)1L;
    }
    public static int LUA_MASKRET() {
        return (int)2L;
    }
    public static int LUA_MASKLINE() {
        return (int)4L;
    }
    public static int LUA_MASKCOUNT() {
        return (int)8L;
    }
    public static MemorySegment LUA_VERSUFFIX() {
        return constants$30.LUA_VERSUFFIX$SEGMENT;
    }
    public static MemorySegment LUA_COLIBNAME() {
        return constants$30.LUA_COLIBNAME$SEGMENT;
    }
    public static MemorySegment LUA_TABLIBNAME() {
        return constants$30.LUA_TABLIBNAME$SEGMENT;
    }
    public static MemorySegment LUA_IOLIBNAME() {
        return constants$30.LUA_IOLIBNAME$SEGMENT;
    }
    public static MemorySegment LUA_OSLIBNAME() {
        return constants$30.LUA_OSLIBNAME$SEGMENT;
    }
    public static MemorySegment LUA_STRLIBNAME() {
        return constants$31.LUA_STRLIBNAME$SEGMENT;
    }
    public static MemorySegment LUA_UTF8LIBNAME() {
        return constants$31.LUA_UTF8LIBNAME$SEGMENT;
    }
    public static MemorySegment LUA_BITLIBNAME() {
        return constants$31.LUA_BITLIBNAME$SEGMENT;
    }
    public static MemorySegment LUA_MATHLIBNAME() {
        return constants$31.LUA_MATHLIBNAME$SEGMENT;
    }
    public static MemorySegment LUA_DBLIBNAME() {
        return constants$31.LUA_DBLIBNAME$SEGMENT;
    }
    public static MemorySegment LUA_LOADLIBNAME() {
        return constants$31.LUA_LOADLIBNAME$SEGMENT;
    }
    public static MemorySegment LUA_ERISLIBNAME() {
        return constants$32.LUA_ERISLIBNAME$SEGMENT;
    }
    public static int LUA_ERRFILE() {
        return (int)7L;
    }
    public static MemorySegment LUA_LOADED_TABLE() {
        return constants$32.LUA_LOADED_TABLE$SEGMENT;
    }
    public static MemorySegment LUA_PRELOAD_TABLE() {
        return constants$32.LUA_PRELOAD_TABLE$SEGMENT;
    }
    public static long LUAL_NUMSIZES() {
        return 136L;
    }
    public static int LUA_NOREF() {
        return (int)-2L;
    }
    public static int LUA_REFNIL() {
        return (int)-1L;
    }
    public static MemorySegment LUA_FILEHANDLE() {
        return constants$32.LUA_FILEHANDLE$SEGMENT;
    }
    public static MemorySegment ERIS_VERSION_MAJOR() {
        return constants$32.ERIS_VERSION_MAJOR$SEGMENT;
    }
    public static MemorySegment ERIS_VERSION_MINOR() {
        return constants$32.ERIS_VERSION_MINOR$SEGMENT;
    }
    public static MemorySegment ERIS_VERSION_RELEASE() {
        return constants$33.ERIS_VERSION_RELEASE$SEGMENT;
    }
}


