// Generated by jextract

package io.github.thecodecrafters.craftingcode.lua.foreign;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface lua_CFunction {

    int apply(jdk.incubator.foreign.MemoryAddress x0);
    static MemoryAddress allocate(lua_CFunction fi) {
        return RuntimeHelper.upcallStub(lua_CFunction.class, fi, constants$0.lua_CFunction$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
    }
    static MemoryAddress allocate(lua_CFunction fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(lua_CFunction.class, fi, constants$0.lua_CFunction$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
    }
    static lua_CFunction ofAddress(MemoryAddress addr) {
        return (jdk.incubator.foreign.MemoryAddress x0) -> {
            try {
                return (int)constants$0.lua_CFunction$MH.invokeExact((Addressable)addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


